apiVersion: v1
kind: Secret
metadata:
  name: git-user-pass
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: RichardW98
  password: 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